force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>Book meta-information.</description>
    <label>Book</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <description>International Standard Book Number</description>
    <label>ISBN</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book_Copy__c/Book_Copy__c.object-meta.xml
<CustomObject>
    <description>Physical copy of a Book</description>
    <label>Book Copy</label>
    <nameField>
        <displayFormat>C{0000}</displayFormat>
        <label>Book Copy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Copies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Copy__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <description>The Book to which the physical book copy belongs</description>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Copies</relationshipLabel>
    <relationshipName>Book_Copies1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book_Copy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Availability of book copy for loan</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Loaned</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestBorrowLogEventTrigger.cls
@isTest
public class TestBorrowLogEventTrigger {
	@isTest
    static void testCreateBorrowLog() {       
        Test.enableChangeDataCapture(); // for all entities
        // Generate test data
        Contact newContact = new Contact(); 
        newContact.LastName = 'Newark';
        newContact.Email = 'newark@email.com';
        
        Book__c newBook = new Book__c();
        newBook.Name = 'The Simpsons';
        newBook.ISBN__c = '1234567891111';

        Database.insert(new sObject[] {newContact, newBook});
        
        Book_Copy__c newBookCopy = new Book_Copy__c(); 
        newBookCopy.Book__c = newBook.Id;       
        insert(newBookCopy);
        
        Borrow_Log__c borrow = new Borrow_Log__c();
        borrow.Contact__c = newContact.Id;
        borrow.Book_Copy__c = newBookCopy.Id;
        borrow.Returned__c = false;        
        insert borrow;
        //     	
        Test.getEventBus().deliver(); // Deliver change event message of type CREATE        
        Book_Copy__c bookCopy = [SELECT Id, Status__c FROM Book_Copy__c WHERE Id = :newBookCopy.Id];
        System.assertEquals('Loaned', bookCopy.Status__c, 'The book copy status did not update to loaned.');
        
        borrow.Returned__c = true;
        update borrow;
        Test.getEventBus().deliver(); // Deliver change event message of type UPDATE
        Book_Copy__c bookCopy2 = [SELECT Id, Status__c FROM Book_Copy__c WHERE Id = :newBookCopy.Id];
        System.assertEquals('Available', bookCopy2.Status__c, 'The book copy status did not update to Available.');        
    }
}